Search.appendIndex(
    [
                {
            "fqsen": "\\Wasm\\Exception\\RuntimeException",
            "name": "RuntimeException",
            "summary": "",
            "url": "classes/Wasm-Exception-RuntimeException.html"
        },                {
            "fqsen": "\\Wasm\\Exception\\InstantiationException",
            "name": "InstantiationException",
            "summary": "",
            "url": "classes/Wasm-Exception-InstantiationException.html"
        },                {
            "fqsen": "\\Wasm\\Exception\\OutOfBoundsException",
            "name": "OutOfBoundsException",
            "summary": "",
            "url": "classes/Wasm-Exception-OutOfBoundsException.html"
        },                {
            "fqsen": "\\wasm_config_new\u0028\u0029",
            "name": "wasm_config_new",
            "summary": "Create\u0020a\u0020new\u0020default\u0020Wasmer\u0020configuration.",
            "url": "namespaces/default.html#function_wasm_config_new"
        },                {
            "fqsen": "\\wasm_config_delete\u0028\u0029",
            "name": "wasm_config_delete",
            "summary": "Delete\u0020a\u0020config\u0020object.",
            "url": "namespaces/default.html#function_wasm_config_delete"
        },                {
            "fqsen": "\\wasm_config_set_compiler\u0028\u0029",
            "name": "wasm_config_set_compiler",
            "summary": "Update\u0020the\u0020configuration\u0020to\u0020specify\u0020a\u0020particular\u0020compiler\u0020to\u0020use.",
            "url": "namespaces/default.html#function_wasm_config_set_compiler"
        },                {
            "fqsen": "\\wasm_config_set_engine\u0028\u0029",
            "name": "wasm_config_set_engine",
            "summary": "Update\u0020the\u0020configuration\u0020to\u0020specify\u0020a\u0020particular\u0020engine\u0020to\u0020use.",
            "url": "namespaces/default.html#function_wasm_config_set_engine"
        },                {
            "fqsen": "\\wasm_engine_new\u0028\u0029",
            "name": "wasm_engine_new",
            "summary": "Create\u0020a\u0020new\u0020JIT\u0020engine\u0020with\u0020the\u0020default\u0020compiler.",
            "url": "namespaces/default.html#function_wasm_engine_new"
        },                {
            "fqsen": "\\wasm_engine_new_with_config\u0028\u0029",
            "name": "wasm_engine_new_with_config",
            "summary": "Create\u0020an\u0020engine\u0020with\u0020a\u0020particular\u0020configuration.",
            "url": "namespaces/default.html#function_wasm_engine_new_with_config"
        },                {
            "fqsen": "\\wasm_engine_delete\u0028\u0029",
            "name": "wasm_engine_delete",
            "summary": "Delete\u0020an\u0020engine.",
            "url": "namespaces/default.html#function_wasm_engine_delete"
        },                {
            "fqsen": "\\wasm_store_new\u0028\u0029",
            "name": "wasm_store_new",
            "summary": "Create\u0020a\u0020new\u0020WebAssembly\u0020store\u0020given\u0020a\u0020specific\u0020engine.",
            "url": "namespaces/default.html#function_wasm_store_new"
        },                {
            "fqsen": "\\wasm_store_delete\u0028\u0029",
            "name": "wasm_store_delete",
            "summary": "Delete\u0020a\u0020store.",
            "url": "namespaces/default.html#function_wasm_store_delete"
        },                {
            "fqsen": "\\wasm_valtype_new\u0028\u0029",
            "name": "wasm_valtype_new",
            "summary": "Create\u0020a\u0020new\u0020valtype.",
            "url": "namespaces/default.html#function_wasm_valtype_new"
        },                {
            "fqsen": "\\wasm_valtype_delete\u0028\u0029",
            "name": "wasm_valtype_delete",
            "summary": "Delete\u0020a\u0020valtype.",
            "url": "namespaces/default.html#function_wasm_valtype_delete"
        },                {
            "fqsen": "\\wasm_valtype_kind\u0028\u0029",
            "name": "wasm_valtype_kind",
            "summary": "Return\u0020the\u0020valtype\u0020kind.",
            "url": "namespaces/default.html#function_wasm_valtype_kind"
        },                {
            "fqsen": "\\wasm_valtype_is_num\u0028\u0029",
            "name": "wasm_valtype_is_num",
            "summary": "Return\u0020\u0060true\u0060\u0020if\u0020the\u0020given\u0020valtype\u0020has\u0020a\u0020numeric\u0020kind.",
            "url": "namespaces/default.html#function_wasm_valtype_is_num"
        },                {
            "fqsen": "\\wasm_valtype_is_ref\u0028\u0029",
            "name": "wasm_valtype_is_ref",
            "summary": "Return\u0020\u0060true\u0060\u0020if\u0020the\u0020given\u0020valtype\u0020has\u0020a\u0020reference\u0020kind.",
            "url": "namespaces/default.html#function_wasm_valtype_is_ref"
        },                {
            "fqsen": "\\wasm_valtype_copy\u0028\u0029",
            "name": "wasm_valtype_copy",
            "summary": "Create\u0020a\u0020copy\u0020of\u0020the\u0020given\u0020valtype.",
            "url": "namespaces/default.html#function_wasm_valtype_copy"
        },                {
            "fqsen": "\\wasm_valkind_is_num\u0028\u0029",
            "name": "wasm_valkind_is_num",
            "summary": "Verify\u0020whether\u0020the\u0020given\u0020kind\u0020is\u0020numeric.",
            "url": "namespaces/default.html#function_wasm_valkind_is_num"
        },                {
            "fqsen": "\\wasm_valkind_is_ref\u0028\u0029",
            "name": "wasm_valkind_is_ref",
            "summary": "Verify\u0020whether\u0020the\u0020given\u0020kind\u0020is\u0020a\u0020reference.",
            "url": "namespaces/default.html#function_wasm_valkind_is_ref"
        },                {
            "fqsen": "\\wasm_functype_new\u0028\u0029",
            "name": "wasm_functype_new",
            "summary": "Create\u0020a\u0020new\u0020valtype.",
            "url": "namespaces/default.html#function_wasm_functype_new"
        },                {
            "fqsen": "\\wasm_functype_delete\u0028\u0029",
            "name": "wasm_functype_delete",
            "summary": "Delete\u0020a\u0020functype.",
            "url": "namespaces/default.html#function_wasm_functype_delete"
        },                {
            "fqsen": "\\wasm_functype_params\u0028\u0029",
            "name": "wasm_functype_params",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_functype_params"
        },                {
            "fqsen": "\\wasm_functype_results\u0028\u0029",
            "name": "wasm_functype_results",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_functype_results"
        },                {
            "fqsen": "\\wasm_functype_copy\u0028\u0029",
            "name": "wasm_functype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_functype_copy"
        },                {
            "fqsen": "\\wasm_functype_as_externtype\u0028\u0029",
            "name": "wasm_functype_as_externtype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_functype_as_externtype"
        },                {
            "fqsen": "\\wasm_globaltype_new\u0028\u0029",
            "name": "wasm_globaltype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_new"
        },                {
            "fqsen": "\\wasm_globaltype_delete\u0028\u0029",
            "name": "wasm_globaltype_delete",
            "summary": "Delete\u0020a\u0020globaltype.",
            "url": "namespaces/default.html#function_wasm_globaltype_delete"
        },                {
            "fqsen": "\\wasm_globaltype_content\u0028\u0029",
            "name": "wasm_globaltype_content",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_content"
        },                {
            "fqsen": "\\wasm_globaltype_mutability\u0028\u0029",
            "name": "wasm_globaltype_mutability",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_mutability"
        },                {
            "fqsen": "\\wasm_globaltype_copy\u0028\u0029",
            "name": "wasm_globaltype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_copy"
        },                {
            "fqsen": "\\wasm_globaltype_as_externtype\u0028\u0029",
            "name": "wasm_globaltype_as_externtype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_as_externtype"
        },                {
            "fqsen": "\\wasm_limits_new\u0028\u0029",
            "name": "wasm_limits_new",
            "summary": "Create\u0020a\u0020new\u0020limits.",
            "url": "namespaces/default.html#function_wasm_limits_new"
        },                {
            "fqsen": "\\wasm_limits_min\u0028\u0029",
            "name": "wasm_limits_min",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_limits_min"
        },                {
            "fqsen": "\\wasm_limits_max\u0028\u0029",
            "name": "wasm_limits_max",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_limits_max"
        },                {
            "fqsen": "\\wasm_tabletype_new\u0028\u0029",
            "name": "wasm_tabletype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_new"
        },                {
            "fqsen": "\\wasm_tabletype_delete\u0028\u0029",
            "name": "wasm_tabletype_delete",
            "summary": "Delete\u0020a\u0020tabletype.",
            "url": "namespaces/default.html#function_wasm_tabletype_delete"
        },                {
            "fqsen": "\\wasm_tabletype_element\u0028\u0029",
            "name": "wasm_tabletype_element",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_element"
        },                {
            "fqsen": "\\wasm_tabletype_limits\u0028\u0029",
            "name": "wasm_tabletype_limits",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_limits"
        },                {
            "fqsen": "\\wasm_tabletype_copy\u0028\u0029",
            "name": "wasm_tabletype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_copy"
        },                {
            "fqsen": "\\wasm_tabletype_as_externtype\u0028\u0029",
            "name": "wasm_tabletype_as_externtype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_as_externtype"
        },                {
            "fqsen": "\\wasm_memorytype_new\u0028\u0029",
            "name": "wasm_memorytype_new",
            "summary": "Create\u0020a\u0020new\u0020memorytype.",
            "url": "namespaces/default.html#function_wasm_memorytype_new"
        },                {
            "fqsen": "\\wasm_memorytype_delete\u0028\u0029",
            "name": "wasm_memorytype_delete",
            "summary": "Delete\u0020a\u0020memorytype.",
            "url": "namespaces/default.html#function_wasm_memorytype_delete"
        },                {
            "fqsen": "\\wasm_memorytype_limits\u0028\u0029",
            "name": "wasm_memorytype_limits",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_memorytype_limits"
        },                {
            "fqsen": "\\wasm_memorytype_copy\u0028\u0029",
            "name": "wasm_memorytype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_memorytype_copy"
        },                {
            "fqsen": "\\wasm_memorytype_as_externtype\u0028\u0029",
            "name": "wasm_memorytype_as_externtype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_memorytype_as_externtype"
        },                {
            "fqsen": "\\wasm_externtype_delete\u0028\u0029",
            "name": "wasm_externtype_delete",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_delete"
        },                {
            "fqsen": "\\wasm_externtype_kind\u0028\u0029",
            "name": "wasm_externtype_kind",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_kind"
        },                {
            "fqsen": "\\wasm_externtype_as_functype\u0028\u0029",
            "name": "wasm_externtype_as_functype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_as_functype"
        },                {
            "fqsen": "\\wasm_externtype_as_globaltype\u0028\u0029",
            "name": "wasm_externtype_as_globaltype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_as_globaltype"
        },                {
            "fqsen": "\\wasm_externtype_as_tabletype\u0028\u0029",
            "name": "wasm_externtype_as_tabletype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_as_tabletype"
        },                {
            "fqsen": "\\wasm_externtype_as_memorytype\u0028\u0029",
            "name": "wasm_externtype_as_memorytype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_as_memorytype"
        },                {
            "fqsen": "\\wasm_importtype_new\u0028\u0029",
            "name": "wasm_importtype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_new"
        },                {
            "fqsen": "\\wasm_importtype_delete\u0028\u0029",
            "name": "wasm_importtype_delete",
            "summary": "Delete\u0020a\u0020importtype.",
            "url": "namespaces/default.html#function_wasm_importtype_delete"
        },                {
            "fqsen": "\\wasm_importtype_module\u0028\u0029",
            "name": "wasm_importtype_module",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_module"
        },                {
            "fqsen": "\\wasm_importtype_name\u0028\u0029",
            "name": "wasm_importtype_name",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_name"
        },                {
            "fqsen": "\\wasm_importtype_type\u0028\u0029",
            "name": "wasm_importtype_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_type"
        },                {
            "fqsen": "\\wasm_importtype_copy\u0028\u0029",
            "name": "wasm_importtype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_copy"
        },                {
            "fqsen": "\\wasm_exporttype_new\u0028\u0029",
            "name": "wasm_exporttype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_exporttype_new"
        },                {
            "fqsen": "\\wasm_exporttype_delete\u0028\u0029",
            "name": "wasm_exporttype_delete",
            "summary": "Delete\u0020a\u0020exporttype.",
            "url": "namespaces/default.html#function_wasm_exporttype_delete"
        },                {
            "fqsen": "\\wasm_exporttype_name\u0028\u0029",
            "name": "wasm_exporttype_name",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_exporttype_name"
        },                {
            "fqsen": "\\wasm_exporttype_type\u0028\u0029",
            "name": "wasm_exporttype_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_exporttype_type"
        },                {
            "fqsen": "\\wasm_exporttype_copy\u0028\u0029",
            "name": "wasm_exporttype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_exporttype_copy"
        },                {
            "fqsen": "\\wasm_val_delete\u0028\u0029",
            "name": "wasm_val_delete",
            "summary": "Delete\u0020a\u0020val.",
            "url": "namespaces/default.html#function_wasm_val_delete"
        },                {
            "fqsen": "\\wasm_val_value\u0028\u0029",
            "name": "wasm_val_value",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_value"
        },                {
            "fqsen": "\\wasm_val_kind\u0028\u0029",
            "name": "wasm_val_kind",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_kind"
        },                {
            "fqsen": "\\wasm_val_copy\u0028\u0029",
            "name": "wasm_val_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_copy"
        },                {
            "fqsen": "\\wasm_val_i32\u0028\u0029",
            "name": "wasm_val_i32",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_i32"
        },                {
            "fqsen": "\\wasm_val_i64\u0028\u0029",
            "name": "wasm_val_i64",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_i64"
        },                {
            "fqsen": "\\wasm_val_f32\u0028\u0029",
            "name": "wasm_val_f32",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_f32"
        },                {
            "fqsen": "\\wasm_val_f64\u0028\u0029",
            "name": "wasm_val_f64",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_f64"
        },                {
            "fqsen": "\\wasm_frame_copy\u0028\u0029",
            "name": "wasm_frame_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_copy"
        },                {
            "fqsen": "\\wasm_frame_instance\u0028\u0029",
            "name": "wasm_frame_instance",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_instance"
        },                {
            "fqsen": "\\wasm_frame_func_index\u0028\u0029",
            "name": "wasm_frame_func_index",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_func_index"
        },                {
            "fqsen": "\\wasm_frame_func_offset\u0028\u0029",
            "name": "wasm_frame_func_offset",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_func_offset"
        },                {
            "fqsen": "\\wasm_frame_module_offset\u0028\u0029",
            "name": "wasm_frame_module_offset",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_module_offset"
        },                {
            "fqsen": "\\wasm_trap_new\u0028\u0029",
            "name": "wasm_trap_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_new"
        },                {
            "fqsen": "\\wasm_trap_delete\u0028\u0029",
            "name": "wasm_trap_delete",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_delete"
        },                {
            "fqsen": "\\wasm_trap_copy\u0028\u0029",
            "name": "wasm_trap_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_copy"
        },                {
            "fqsen": "\\wasm_trap_message\u0028\u0029",
            "name": "wasm_trap_message",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_message"
        },                {
            "fqsen": "\\wasm_trap_origin\u0028\u0029",
            "name": "wasm_trap_origin",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_origin"
        },                {
            "fqsen": "\\wasm_trap_trace\u0028\u0029",
            "name": "wasm_trap_trace",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_trace"
        },                {
            "fqsen": "\\wasm_module_new\u0028\u0029",
            "name": "wasm_module_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_new"
        },                {
            "fqsen": "\\wasm_module_delete\u0028\u0029",
            "name": "wasm_module_delete",
            "summary": "Delete\u0020a\u0020module.",
            "url": "namespaces/default.html#function_wasm_module_delete"
        },                {
            "fqsen": "\\wasm_module_validate\u0028\u0029",
            "name": "wasm_module_validate",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_validate"
        },                {
            "fqsen": "\\wasm_module_imports\u0028\u0029",
            "name": "wasm_module_imports",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_imports"
        },                {
            "fqsen": "\\wasm_module_exports\u0028\u0029",
            "name": "wasm_module_exports",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_exports"
        },                {
            "fqsen": "\\wasm_module_serialize\u0028\u0029",
            "name": "wasm_module_serialize",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_serialize"
        },                {
            "fqsen": "\\wasm_module_deserialize\u0028\u0029",
            "name": "wasm_module_deserialize",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_deserialize"
        },                {
            "fqsen": "\\wasm_module_name\u0028\u0029",
            "name": "wasm_module_name",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_name"
        },                {
            "fqsen": "\\wasm_module_set_name\u0028\u0029",
            "name": "wasm_module_set_name",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_set_name"
        },                {
            "fqsen": "\\wasm_module_copy\u0028\u0029",
            "name": "wasm_module_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_copy"
        },                {
            "fqsen": "\\wasm_func_new\u0028\u0029",
            "name": "wasm_func_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_new"
        },                {
            "fqsen": "\\wasm_func_delete\u0028\u0029",
            "name": "wasm_func_delete",
            "summary": "Delete\u0020a\u0020func.",
            "url": "namespaces/default.html#function_wasm_func_delete"
        },                {
            "fqsen": "\\wasm_func_type\u0028\u0029",
            "name": "wasm_func_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_type"
        },                {
            "fqsen": "\\wasm_func_param_arity\u0028\u0029",
            "name": "wasm_func_param_arity",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_param_arity"
        },                {
            "fqsen": "\\wasm_func_result_arity\u0028\u0029",
            "name": "wasm_func_result_arity",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_result_arity"
        },                {
            "fqsen": "\\wasm_func_call\u0028\u0029",
            "name": "wasm_func_call",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_call"
        },                {
            "fqsen": "\\wasm_func_as_extern\u0028\u0029",
            "name": "wasm_func_as_extern",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_as_extern"
        },                {
            "fqsen": "\\wasm_global_new\u0028\u0029",
            "name": "wasm_global_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_new"
        },                {
            "fqsen": "\\wasm_global_delete\u0028\u0029",
            "name": "wasm_global_delete",
            "summary": "Delete\u0020a\u0020global.",
            "url": "namespaces/default.html#function_wasm_global_delete"
        },                {
            "fqsen": "\\wasm_global_type\u0028\u0029",
            "name": "wasm_global_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_type"
        },                {
            "fqsen": "\\wasm_global_get\u0028\u0029",
            "name": "wasm_global_get",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_get"
        },                {
            "fqsen": "\\wasm_global_set\u0028\u0029",
            "name": "wasm_global_set",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_set"
        },                {
            "fqsen": "\\wasm_global_copy\u0028\u0029",
            "name": "wasm_global_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_copy"
        },                {
            "fqsen": "\\wasm_global_same\u0028\u0029",
            "name": "wasm_global_same",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_same"
        },                {
            "fqsen": "\\wasm_global_as_extern\u0028\u0029",
            "name": "wasm_global_as_extern",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_as_extern"
        },                {
            "fqsen": "\\wasm_extern_delete\u0028\u0029",
            "name": "wasm_extern_delete",
            "summary": "Delete\u0020an\u0020extern.",
            "url": "namespaces/default.html#function_wasm_extern_delete"
        },                {
            "fqsen": "\\wasm_extern_kind\u0028\u0029",
            "name": "wasm_extern_kind",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_kind"
        },                {
            "fqsen": "\\wasm_extern_type\u0028\u0029",
            "name": "wasm_extern_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_type"
        },                {
            "fqsen": "\\wasm_extern_as_func\u0028\u0029",
            "name": "wasm_extern_as_func",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_as_func"
        },                {
            "fqsen": "\\wasm_extern_as_global\u0028\u0029",
            "name": "wasm_extern_as_global",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_as_global"
        },                {
            "fqsen": "\\wasm_extern_as_table\u0028\u0029",
            "name": "wasm_extern_as_table",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_as_table"
        },                {
            "fqsen": "\\wasm_extern_as_memory\u0028\u0029",
            "name": "wasm_extern_as_memory",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_as_memory"
        },                {
            "fqsen": "\\wasm_instance_new\u0028\u0029",
            "name": "wasm_instance_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_instance_new"
        },                {
            "fqsen": "\\wasm_instance_delete\u0028\u0029",
            "name": "wasm_instance_delete",
            "summary": "Delete\u0020an\u0020instance.",
            "url": "namespaces/default.html#function_wasm_instance_delete"
        },                {
            "fqsen": "\\wasm_instance_exports\u0028\u0029",
            "name": "wasm_instance_exports",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_instance_exports"
        },                {
            "fqsen": "\\wasm_instance_copy\u0028\u0029",
            "name": "wasm_instance_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_instance_copy"
        },                {
            "fqsen": "\\wasmer_version\u0028\u0029",
            "name": "wasmer_version",
            "summary": "Return\u0020the\u0020version\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version"
        },                {
            "fqsen": "\\wasmer_version_major\u0028\u0029",
            "name": "wasmer_version_major",
            "summary": "Return\u0020the\u0020major\u0020version\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version_major"
        },                {
            "fqsen": "\\wasmer_version_minor\u0028\u0029",
            "name": "wasmer_version_minor",
            "summary": "Return\u0020the\u0020minor\u0020version\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version_minor"
        },                {
            "fqsen": "\\wasmer_version_patch\u0028\u0029",
            "name": "wasmer_version_patch",
            "summary": "Return\u0020the\u0020patch\u0020version\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version_patch"
        },                {
            "fqsen": "\\wasmer_version_pre\u0028\u0029",
            "name": "wasmer_version_pre",
            "summary": "Return\u0020the\u0020pre\u002Drelease\u0020label\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version_pre"
        },                {
            "fqsen": "\\wat2wasm\u0028\u0029",
            "name": "wat2wasm",
            "summary": "\u26A0\uFE0F\u0020This\u0020is\u0020a\u0020Wasmer\u002Dspecific\u0020function.",
            "url": "namespaces/default.html#function_wat2wasm"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType",
            "name": "ExportType",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType",
            "name": "ExternType",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType",
            "name": "FuncType",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType",
            "name": "GlobalType",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType",
            "name": "ImportType",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType",
            "name": "MemoryType",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType",
            "name": "TableType",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType",
            "name": "ValType",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern",
            "name": "Extern",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame",
            "name": "Frame",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val",
            "name": "Val",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Wasm-Config.html"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Config\u0020from\u0020a\u0020\u0060wasm_config_t\u0060\u0020resource.",
            "url": "classes/Wasm-Config.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020config\u0020resource.",
            "url": "classes/Wasm-Config.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003AsetCompiler\u0028\u0029",
            "name": "setCompiler",
            "summary": "Set\u0020the\u0020compiler\u0020for\u0020the\u0020current\u0020configuration.",
            "url": "classes/Wasm-Config.html#method_setCompiler"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003AsetEngine\u0028\u0029",
            "name": "setEngine",
            "summary": "Set\u0020the\u0020engine\u0020for\u0020the\u0020current\u0020configuration.",
            "url": "classes/Wasm-Config.html#method_setEngine"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Config.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003ACOMPILER_CRANELIFT",
            "name": "COMPILER_CRANELIFT",
            "summary": "",
            "url": "classes/Wasm-Config.html#constant_COMPILER_CRANELIFT"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003ACOMPILER_LLVM",
            "name": "COMPILER_LLVM",
            "summary": "",
            "url": "classes/Wasm-Config.html#constant_COMPILER_LLVM"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003ACOMPILER_SINGLEPASS",
            "name": "COMPILER_SINGLEPASS",
            "summary": "",
            "url": "classes/Wasm-Config.html#constant_COMPILER_SINGLEPASS"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003AENGINE_JIT",
            "name": "ENGINE_JIT",
            "summary": "",
            "url": "classes/Wasm-Config.html#constant_ENGINE_JIT"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003AENGINE_NATIVE",
            "name": "ENGINE_NATIVE",
            "summary": "",
            "url": "classes/Wasm-Config.html#constant_ENGINE_NATIVE"
        },                {
            "fqsen": "\\Wasm\\Config\u003A\u003AENGINE_OBJECT_FILE",
            "name": "ENGINE_OBJECT_FILE",
            "summary": "",
            "url": "classes/Wasm-Config.html#constant_ENGINE_OBJECT_FILE"
        },                {
            "fqsen": "\\Wasm\\Engine",
            "name": "Engine",
            "summary": "",
            "url": "classes/Wasm-Engine.html"
        },                {
            "fqsen": "\\Wasm\\Engine\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Engine.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Engine\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Wasm-Engine.html#method___destruct"
        },                {
            "fqsen": "\\Wasm\\Engine\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "",
            "url": "classes/Wasm-Engine.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Engine\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Engine.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/Wasm-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\Wasm\\Module\\Extern",
            "name": "Extern",
            "summary": "",
            "url": "classes/Wasm-Module-Extern.html"
        },                {
            "fqsen": "\\Wasm\\Module\\Extern\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Module\\Extern\u0020from\u0020a\u0020\u0060wasm_extern_t\u0060\u0020resource.",
            "url": "classes/Wasm-Module-Extern.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Module\\Extern\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020extern\u0020resource.",
            "url": "classes/Wasm-Module-Extern.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Module\\Extern\u003A\u003AasFunc\u0028\u0029",
            "name": "asFunc",
            "summary": "",
            "url": "classes/Wasm-Module-Extern.html#method_asFunc"
        },                {
            "fqsen": "\\Wasm\\Module\\Extern\u003A\u003AasGlobal\u0028\u0029",
            "name": "asGlobal",
            "summary": "",
            "url": "classes/Wasm-Module-Extern.html#method_asGlobal"
        },                {
            "fqsen": "\\Wasm\\Module\\Extern\u003A\u003Akind\u0028\u0029",
            "name": "kind",
            "summary": "",
            "url": "classes/Wasm-Module-Extern.html#method_kind"
        },                {
            "fqsen": "\\Wasm\\Module\\Extern\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Wasm-Module-Extern.html#method_type"
        },                {
            "fqsen": "\\Wasm\\Module\\Func",
            "name": "Func",
            "summary": "",
            "url": "classes/Wasm-Module-Func.html"
        },                {
            "fqsen": "\\Wasm\\Module\\Func\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Module\\Func\u0020from\u0020a\u0020\u0060wasm_func_t\u0060\u0020resource.",
            "url": "classes/Wasm-Module-Func.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Module\\Func\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/Wasm-Module-Func.html#method___invoke"
        },                {
            "fqsen": "\\Wasm\\Module\\Func\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020func\u0020resource.",
            "url": "classes/Wasm-Module-Func.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Module\\Func\u003A\u003AasExtern\u0028\u0029",
            "name": "asExtern",
            "summary": "",
            "url": "classes/Wasm-Module-Func.html#method_asExtern"
        },                {
            "fqsen": "\\Wasm\\Module\\Func\u003A\u003AparamArity\u0028\u0029",
            "name": "paramArity",
            "summary": "",
            "url": "classes/Wasm-Module-Func.html#method_paramArity"
        },                {
            "fqsen": "\\Wasm\\Module\\Func\u003A\u003AresultArity\u0028\u0029",
            "name": "resultArity",
            "summary": "",
            "url": "classes/Wasm-Module-Func.html#method_resultArity"
        },                {
            "fqsen": "\\Wasm\\Module\\Func\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Wasm-Module-Func.html#method_type"
        },                {
            "fqsen": "\\Wasm\\Module\\Func\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Module-Func.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl",
            "name": "Globl",
            "summary": "",
            "url": "classes/Wasm-Module-Globl.html"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Module\\Globl\u0020from\u0020a\u0020\u0060wasm_global_t\u0060\u0020resource.",
            "url": "classes/Wasm-Module-Globl.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020global\u0020resource.",
            "url": "classes/Wasm-Module-Globl.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl\u003A\u003AasExtern\u0028\u0029",
            "name": "asExtern",
            "summary": "",
            "url": "classes/Wasm-Module-Globl.html#method_asExtern"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Wasm-Module-Globl.html#method_get"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl\u003A\u003Asame\u0028\u0029",
            "name": "same",
            "summary": "",
            "url": "classes/Wasm-Module-Globl.html#method_same"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/Wasm-Module-Globl.html#method_set"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Wasm-Module-Globl.html#method_type"
        },                {
            "fqsen": "\\Wasm\\Module\\Globl\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Module-Globl.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Module\\Instance",
            "name": "Instance",
            "summary": "",
            "url": "classes/Wasm-Module-Instance.html"
        },                {
            "fqsen": "\\Wasm\\Module\\Instance\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Module\\Extern\u0020from\u0020a\u0020\u0060wasm_instance_t\u0060\u0020resource.",
            "url": "classes/Wasm-Module-Instance.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Module\\Instance\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020extern\u0020resource.",
            "url": "classes/Wasm-Module-Instance.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Module\\Instance\u003A\u003Aexports\u0028\u0029",
            "name": "exports",
            "summary": "",
            "url": "classes/Wasm-Module-Instance.html#method_exports"
        },                {
            "fqsen": "\\Wasm\\Module\\Instance\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Module-Instance.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Module\\Val",
            "name": "Val",
            "summary": "",
            "url": "classes/Wasm-Module-Val.html"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Module\\Val\u0020from\u0020a\u0020\u0060wasm_val_t\u0060\u0020resource.",
            "url": "classes/Wasm-Module-Val.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020val\u0020resource.",
            "url": "classes/Wasm-Module-Val.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003Akind\u0028\u0029",
            "name": "kind",
            "summary": "",
            "url": "classes/Wasm-Module-Val.html#method_kind"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003Avalue\u0028\u0029",
            "name": "value",
            "summary": "",
            "url": "classes/Wasm-Module-Val.html#method_value"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Module-Val.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003AnewI32\u0028\u0029",
            "name": "newI32",
            "summary": "",
            "url": "classes/Wasm-Module-Val.html#method_newI32"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003AnewI64\u0028\u0029",
            "name": "newI64",
            "summary": "",
            "url": "classes/Wasm-Module-Val.html#method_newI64"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003AnewF32\u0028\u0029",
            "name": "newF32",
            "summary": "",
            "url": "classes/Wasm-Module-Val.html#method_newF32"
        },                {
            "fqsen": "\\Wasm\\Module\\Val\u003A\u003AnewF64\u0028\u0029",
            "name": "newF64",
            "summary": "",
            "url": "classes/Wasm-Module-Val.html#method_newF64"
        },                {
            "fqsen": "\\Wasm\\Module",
            "name": "Module",
            "summary": "",
            "url": "classes/Wasm-Module.html"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Module\u0020from\u0020a\u0020\u0060wasm_module_t\u0060\u0020resource.",
            "url": "classes/Wasm-Module.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020module\u0020resource.",
            "url": "classes/Wasm-Module.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003Aexports\u0028\u0029",
            "name": "exports",
            "summary": "",
            "url": "classes/Wasm-Module.html#method_exports"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003Aimports\u0028\u0029",
            "name": "imports",
            "summary": "",
            "url": "classes/Wasm-Module.html#method_imports"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "Get\u0020or\u0020set\u0020the\u0020module\u0027s\u0020name.",
            "url": "classes/Wasm-Module.html#method_name"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Wasm-Module.html#method_serialize"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003Adeserialize\u0028\u0029",
            "name": "deserialize",
            "summary": "",
            "url": "classes/Wasm-Module.html#method_deserialize"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Module.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Module\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "",
            "url": "classes/Wasm-Module.html#method_validate"
        },                {
            "fqsen": "\\Wasm\\Store",
            "name": "Store",
            "summary": "",
            "url": "classes/Wasm-Store.html"
        },                {
            "fqsen": "\\Wasm\\Store\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Store\u0020from\u0020a\u0020\u0060wasm_store_t\u0060\u0020resource.",
            "url": "classes/Wasm-Store.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Store\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Wasm-Store.html#method___destruct"
        },                {
            "fqsen": "\\Wasm\\Store\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "",
            "url": "classes/Wasm-Store.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Store\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Store.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType",
            "name": "ExternType",
            "summary": "",
            "url": "classes/Wasm-Type-ExternType.html"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Type\\ExternType\u0020from\u0020a\u0020\u0060wasm_externtype_t\u0060\u0020resource.",
            "url": "classes/Wasm-Type-ExternType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020extern\u0020type\u0020resource.",
            "url": "classes/Wasm-Type-ExternType.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003AasGlobalType\u0028\u0029",
            "name": "asGlobalType",
            "summary": "",
            "url": "classes/Wasm-Type-ExternType.html#method_asGlobalType"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003AasFuncType\u0028\u0029",
            "name": "asFuncType",
            "summary": "",
            "url": "classes/Wasm-Type-ExternType.html#method_asFuncType"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003Akind\u0028\u0029",
            "name": "kind",
            "summary": "",
            "url": "classes/Wasm-Type-ExternType.html#method_kind"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003AKIND_FUNC",
            "name": "KIND_FUNC",
            "summary": "",
            "url": "classes/Wasm-Type-ExternType.html#constant_KIND_FUNC"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003AKIND_GLOBAL",
            "name": "KIND_GLOBAL",
            "summary": "",
            "url": "classes/Wasm-Type-ExternType.html#constant_KIND_GLOBAL"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003AKIND_TABLE",
            "name": "KIND_TABLE",
            "summary": "",
            "url": "classes/Wasm-Type-ExternType.html#constant_KIND_TABLE"
        },                {
            "fqsen": "\\Wasm\\Type\\ExternType\u003A\u003AKIND_MEMORY",
            "name": "KIND_MEMORY",
            "summary": "",
            "url": "classes/Wasm-Type-ExternType.html#constant_KIND_MEMORY"
        },                {
            "fqsen": "\\Wasm\\Type\\FuncType",
            "name": "FuncType",
            "summary": "Function\u0020types\u0020classify\u0020the\u0020signature\u0020of\u0020functions,\u0020mapping\u0020a\u0020vector\u0020of\u0020parameters\u0020to\u0020a\u0020vector\u0020of\u0020results.\u0020They\u0020are\nalso\u0020used\u0020to\u0020classify\u0020the\u0020inputs\u0020and\u0020outputs\u0020of\u0020instructions.",
            "url": "classes/Wasm-Type-FuncType.html"
        },                {
            "fqsen": "\\Wasm\\Type\\FuncType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Type\\FuncType\u0020from\u0020a\u0020\u0060wasm_functype_t\u0060\u0020resource.",
            "url": "classes/Wasm-Type-FuncType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Type\\FuncType\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020function\u0020type\u0020resource.",
            "url": "classes/Wasm-Type-FuncType.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Type\\FuncType\u003A\u003AasExternType\u0028\u0029",
            "name": "asExternType",
            "summary": "",
            "url": "classes/Wasm-Type-FuncType.html#method_asExternType"
        },                {
            "fqsen": "\\Wasm\\Type\\FuncType\u003A\u003Aparams\u0028\u0029",
            "name": "params",
            "summary": "",
            "url": "classes/Wasm-Type-FuncType.html#method_params"
        },                {
            "fqsen": "\\Wasm\\Type\\FuncType\u003A\u003Aresults\u0028\u0029",
            "name": "results",
            "summary": "",
            "url": "classes/Wasm-Type-FuncType.html#method_results"
        },                {
            "fqsen": "\\Wasm\\Type\\FuncType\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Type-FuncType.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType",
            "name": "GlobalType",
            "summary": "Global\u0020types\u0020classify\u0020global\u0020variables,\u0020which\u0020hold\u0020a\u0020value\u0020and\u0020can\u0020either\u0020be\u0020mutable\u0020or\u0020immutable.",
            "url": "classes/Wasm-Type-GlobalType.html"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Type\\GlobalType\u0020from\u0020a\u0020\u0060wasm_globaltype_t\u0060\u0020resource.",
            "url": "classes/Wasm-Type-GlobalType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020global\u0020type\u0020resource.",
            "url": "classes/Wasm-Type-GlobalType.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType\u003A\u003AasExternType\u0028\u0029",
            "name": "asExternType",
            "summary": "",
            "url": "classes/Wasm-Type-GlobalType.html#method_asExternType"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType\u003A\u003Amutability\u0028\u0029",
            "name": "mutability",
            "summary": "Return\u0020the\u0020global\u0020type\u0027s\u0020mutability.",
            "url": "classes/Wasm-Type-GlobalType.html#method_mutability"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Wasm-Type-GlobalType.html#method_content"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Type-GlobalType.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType\u003A\u003AMUTABILITY_VAR",
            "name": "MUTABILITY_VAR",
            "summary": "",
            "url": "classes/Wasm-Type-GlobalType.html#constant_MUTABILITY_VAR"
        },                {
            "fqsen": "\\Wasm\\Type\\GlobalType\u003A\u003AMUTABILITY_CONST",
            "name": "MUTABILITY_CONST",
            "summary": "",
            "url": "classes/Wasm-Type-GlobalType.html#constant_MUTABILITY_CONST"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType",
            "name": "ValType",
            "summary": "Value\u0020types\u0020classify\u0020the\u0020individual\u0020values\u0020that\u0020WebAssembly\u0020code\u0020can\u0020compute\u0020with\u0020and\u0020the\u0020values\u0020that\u0020a\u0020variable\u0020accepts.",
            "url": "classes/Wasm-Type-ValType.html"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Wasm\\Type\\ValType\u0020from\u0020a\u0020\u0060wasm_valtype_t\u0060\u0020resource.",
            "url": "classes/Wasm-Type-ValType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003Ainner\u0028\u0029",
            "name": "inner",
            "summary": "Return\u0020the\u0020inner\u0020value\u0020type\u0020resource.",
            "url": "classes/Wasm-Type-ValType.html#method_inner"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003AisNum\u0028\u0029",
            "name": "isNum",
            "summary": "Check\u0020if\u0020the\u0020value\u0020type\u0020is\u0020a\u0020numeric\u0020type.",
            "url": "classes/Wasm-Type-ValType.html#method_isNum"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003AisRef\u0028\u0029",
            "name": "isRef",
            "summary": "Check\u0020if\u0020the\u0020value\u0020type\u0020is\u0020a\u0020reference\u0020type.",
            "url": "classes/Wasm-Type-ValType.html#method_isRef"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003Akind\u0028\u0029",
            "name": "kind",
            "summary": "Check\u0020the\u0020value\u0020type\u0027s\u0020type.",
            "url": "classes/Wasm-Type-ValType.html#method_kind"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/Wasm-Type-ValType.html#method_new"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003AKIND_I32",
            "name": "KIND_I32",
            "summary": "",
            "url": "classes/Wasm-Type-ValType.html#constant_KIND_I32"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003AKIND_I64",
            "name": "KIND_I64",
            "summary": "",
            "url": "classes/Wasm-Type-ValType.html#constant_KIND_I64"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003AKIND_F32",
            "name": "KIND_F32",
            "summary": "",
            "url": "classes/Wasm-Type-ValType.html#constant_KIND_F32"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003AKIND_F64",
            "name": "KIND_F64",
            "summary": "",
            "url": "classes/Wasm-Type-ValType.html#constant_KIND_F64"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003AKIND_ANYREF",
            "name": "KIND_ANYREF",
            "summary": "",
            "url": "classes/Wasm-Type-ValType.html#constant_KIND_ANYREF"
        },                {
            "fqsen": "\\Wasm\\Type\\ValType\u003A\u003AKIND_FUNCREF",
            "name": "KIND_FUNCREF",
            "summary": "",
            "url": "classes/Wasm-Type-ValType.html#constant_KIND_FUNCREF"
        },                {
            "fqsen": "\\Wasm\\Wat",
            "name": "Wat",
            "summary": "",
            "url": "classes/Wasm-Wat.html"
        },                {
            "fqsen": "\\Wasm\\Wat\u003A\u003Awasm\u0028\u0029",
            "name": "wasm",
            "summary": "",
            "url": "classes/Wasm-Wat.html#method_wasm"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Wasm\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/wasm-exception.html"
        },                {
            "fqsen": "\\Wasm\\Vec",
            "name": "Vec",
            "summary": "",
            "url": "namespaces/wasm-vec.html"
        },                {
            "fqsen": "\\Wasm",
            "name": "Wasm",
            "summary": "",
            "url": "namespaces/wasm.html"
        },                {
            "fqsen": "\\Wasm\\Module",
            "name": "Module",
            "summary": "",
            "url": "namespaces/wasm-module.html"
        },                {
            "fqsen": "\\Wasm\\Type",
            "name": "Type",
            "summary": "",
            "url": "namespaces/wasm-type.html"
        }            ]
);
