Search.appendIndex(
    [
                {
            "fqsen": "\\Wasm\\Exception\\RuntimeException",
            "name": "RuntimeException",
            "summary": "",
            "url": "classes/Wasm-Exception-RuntimeException.html"
        },                {
            "fqsen": "\\Wasm\\Exception\\InstantiationException",
            "name": "InstantiationException",
            "summary": "",
            "url": "classes/Wasm-Exception-InstantiationException.html"
        },                {
            "fqsen": "\\Wasm\\Exception\\OutOfBoundsException",
            "name": "OutOfBoundsException",
            "summary": "",
            "url": "classes/Wasm-Exception-OutOfBoundsException.html"
        },                {
            "fqsen": "\\wasm_config_new\u0028\u0029",
            "name": "wasm_config_new",
            "summary": "Create\u0020a\u0020new\u0020default\u0020Wasmer\u0020configuration.",
            "url": "namespaces/default.html#function_wasm_config_new"
        },                {
            "fqsen": "\\wasm_config_delete\u0028\u0029",
            "name": "wasm_config_delete",
            "summary": "Delete\u0020a\u0020config\u0020object.",
            "url": "namespaces/default.html#function_wasm_config_delete"
        },                {
            "fqsen": "\\wasm_config_set_compiler\u0028\u0029",
            "name": "wasm_config_set_compiler",
            "summary": "Update\u0020the\u0020configuration\u0020to\u0020specify\u0020a\u0020particular\u0020compiler\u0020to\u0020use.",
            "url": "namespaces/default.html#function_wasm_config_set_compiler"
        },                {
            "fqsen": "\\wasm_config_set_engine\u0028\u0029",
            "name": "wasm_config_set_engine",
            "summary": "Update\u0020the\u0020configuration\u0020to\u0020specify\u0020a\u0020particular\u0020engine\u0020to\u0020use.",
            "url": "namespaces/default.html#function_wasm_config_set_engine"
        },                {
            "fqsen": "\\wasm_engine_new\u0028\u0029",
            "name": "wasm_engine_new",
            "summary": "Create\u0020a\u0020new\u0020JIT\u0020engine\u0020with\u0020the\u0020default\u0020compiler.",
            "url": "namespaces/default.html#function_wasm_engine_new"
        },                {
            "fqsen": "\\wasm_engine_new_with_config\u0028\u0029",
            "name": "wasm_engine_new_with_config",
            "summary": "Create\u0020an\u0020engine\u0020with\u0020a\u0020particular\u0020configuration.",
            "url": "namespaces/default.html#function_wasm_engine_new_with_config"
        },                {
            "fqsen": "\\wasm_engine_delete\u0028\u0029",
            "name": "wasm_engine_delete",
            "summary": "Delete\u0020an\u0020engine.",
            "url": "namespaces/default.html#function_wasm_engine_delete"
        },                {
            "fqsen": "\\wasm_store_new\u0028\u0029",
            "name": "wasm_store_new",
            "summary": "Create\u0020a\u0020new\u0020WebAssembly\u0020store\u0020given\u0020a\u0020specific\u0020engine.",
            "url": "namespaces/default.html#function_wasm_store_new"
        },                {
            "fqsen": "\\wasm_store_delete\u0028\u0029",
            "name": "wasm_store_delete",
            "summary": "Delete\u0020a\u0020store.",
            "url": "namespaces/default.html#function_wasm_store_delete"
        },                {
            "fqsen": "\\wasm_valtype_new\u0028\u0029",
            "name": "wasm_valtype_new",
            "summary": "Create\u0020a\u0020new\u0020valtype.",
            "url": "namespaces/default.html#function_wasm_valtype_new"
        },                {
            "fqsen": "\\wasm_valtype_delete\u0028\u0029",
            "name": "wasm_valtype_delete",
            "summary": "Delete\u0020a\u0020valtype.",
            "url": "namespaces/default.html#function_wasm_valtype_delete"
        },                {
            "fqsen": "\\wasm_valtype_kind\u0028\u0029",
            "name": "wasm_valtype_kind",
            "summary": "Return\u0020the\u0020valtype\u0020kind.",
            "url": "namespaces/default.html#function_wasm_valtype_kind"
        },                {
            "fqsen": "\\wasm_valtype_is_num\u0028\u0029",
            "name": "wasm_valtype_is_num",
            "summary": "Return\u0020\u0060true\u0060\u0020if\u0020the\u0020given\u0020valtype\u0020has\u0020a\u0020numeric\u0020kind.",
            "url": "namespaces/default.html#function_wasm_valtype_is_num"
        },                {
            "fqsen": "\\wasm_valtype_is_ref\u0028\u0029",
            "name": "wasm_valtype_is_ref",
            "summary": "Return\u0020\u0060true\u0060\u0020if\u0020the\u0020given\u0020valtype\u0020has\u0020a\u0020reference\u0020kind.",
            "url": "namespaces/default.html#function_wasm_valtype_is_ref"
        },                {
            "fqsen": "\\wasm_valtype_copy\u0028\u0029",
            "name": "wasm_valtype_copy",
            "summary": "Create\u0020a\u0020copy\u0020of\u0020the\u0020given\u0020valtype.",
            "url": "namespaces/default.html#function_wasm_valtype_copy"
        },                {
            "fqsen": "\\wasm_valkind_is_num\u0028\u0029",
            "name": "wasm_valkind_is_num",
            "summary": "Verify\u0020whether\u0020the\u0020given\u0020kind\u0020is\u0020numeric.",
            "url": "namespaces/default.html#function_wasm_valkind_is_num"
        },                {
            "fqsen": "\\wasm_valkind_is_ref\u0028\u0029",
            "name": "wasm_valkind_is_ref",
            "summary": "Verify\u0020whether\u0020the\u0020given\u0020kind\u0020is\u0020a\u0020reference.",
            "url": "namespaces/default.html#function_wasm_valkind_is_ref"
        },                {
            "fqsen": "\\wasm_functype_new\u0028\u0029",
            "name": "wasm_functype_new",
            "summary": "Create\u0020a\u0020new\u0020valtype.",
            "url": "namespaces/default.html#function_wasm_functype_new"
        },                {
            "fqsen": "\\wasm_functype_delete\u0028\u0029",
            "name": "wasm_functype_delete",
            "summary": "Delete\u0020a\u0020functype.",
            "url": "namespaces/default.html#function_wasm_functype_delete"
        },                {
            "fqsen": "\\wasm_functype_params\u0028\u0029",
            "name": "wasm_functype_params",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_functype_params"
        },                {
            "fqsen": "\\wasm_functype_results\u0028\u0029",
            "name": "wasm_functype_results",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_functype_results"
        },                {
            "fqsen": "\\wasm_functype_copy\u0028\u0029",
            "name": "wasm_functype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_functype_copy"
        },                {
            "fqsen": "\\wasm_functype_as_externtype\u0028\u0029",
            "name": "wasm_functype_as_externtype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_functype_as_externtype"
        },                {
            "fqsen": "\\wasm_globaltype_new\u0028\u0029",
            "name": "wasm_globaltype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_new"
        },                {
            "fqsen": "\\wasm_globaltype_delete\u0028\u0029",
            "name": "wasm_globaltype_delete",
            "summary": "Delete\u0020a\u0020globaltype.",
            "url": "namespaces/default.html#function_wasm_globaltype_delete"
        },                {
            "fqsen": "\\wasm_globaltype_content\u0028\u0029",
            "name": "wasm_globaltype_content",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_content"
        },                {
            "fqsen": "\\wasm_globaltype_mutability\u0028\u0029",
            "name": "wasm_globaltype_mutability",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_mutability"
        },                {
            "fqsen": "\\wasm_globaltype_copy\u0028\u0029",
            "name": "wasm_globaltype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_copy"
        },                {
            "fqsen": "\\wasm_globaltype_as_externtype\u0028\u0029",
            "name": "wasm_globaltype_as_externtype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_globaltype_as_externtype"
        },                {
            "fqsen": "\\wasm_limits_new\u0028\u0029",
            "name": "wasm_limits_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_limits_new"
        },                {
            "fqsen": "\\wasm_limits_min\u0028\u0029",
            "name": "wasm_limits_min",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_limits_min"
        },                {
            "fqsen": "\\wasm_limits_max\u0028\u0029",
            "name": "wasm_limits_max",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_limits_max"
        },                {
            "fqsen": "\\wasm_tabletype_new\u0028\u0029",
            "name": "wasm_tabletype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_new"
        },                {
            "fqsen": "\\wasm_tabletype_delete\u0028\u0029",
            "name": "wasm_tabletype_delete",
            "summary": "Delete\u0020a\u0020tabletype.",
            "url": "namespaces/default.html#function_wasm_tabletype_delete"
        },                {
            "fqsen": "\\wasm_tabletype_element\u0028\u0029",
            "name": "wasm_tabletype_element",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_element"
        },                {
            "fqsen": "\\wasm_tabletype_limits\u0028\u0029",
            "name": "wasm_tabletype_limits",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_limits"
        },                {
            "fqsen": "\\wasm_tabletype_copy\u0028\u0029",
            "name": "wasm_tabletype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_copy"
        },                {
            "fqsen": "\\wasm_tabletype_as_externtype\u0028\u0029",
            "name": "wasm_tabletype_as_externtype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_tabletype_as_externtype"
        },                {
            "fqsen": "\\wasm_memorytype_new\u0028\u0029",
            "name": "wasm_memorytype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_memorytype_new"
        },                {
            "fqsen": "\\wasm_memorytype_delete\u0028\u0029",
            "name": "wasm_memorytype_delete",
            "summary": "Delete\u0020a\u0020memorytype.",
            "url": "namespaces/default.html#function_wasm_memorytype_delete"
        },                {
            "fqsen": "\\wasm_memorytype_limits\u0028\u0029",
            "name": "wasm_memorytype_limits",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_memorytype_limits"
        },                {
            "fqsen": "\\wasm_memorytype_copy\u0028\u0029",
            "name": "wasm_memorytype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_memorytype_copy"
        },                {
            "fqsen": "\\wasm_memorytype_as_externtype\u0028\u0029",
            "name": "wasm_memorytype_as_externtype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_memorytype_as_externtype"
        },                {
            "fqsen": "\\wasm_externtype_kind\u0028\u0029",
            "name": "wasm_externtype_kind",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_kind"
        },                {
            "fqsen": "\\wasm_externtype_as_functype\u0028\u0029",
            "name": "wasm_externtype_as_functype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_as_functype"
        },                {
            "fqsen": "\\wasm_externtype_as_globaltype\u0028\u0029",
            "name": "wasm_externtype_as_globaltype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_as_globaltype"
        },                {
            "fqsen": "\\wasm_externtype_as_tabletype\u0028\u0029",
            "name": "wasm_externtype_as_tabletype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_as_tabletype"
        },                {
            "fqsen": "\\wasm_externtype_as_memorytype\u0028\u0029",
            "name": "wasm_externtype_as_memorytype",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_externtype_as_memorytype"
        },                {
            "fqsen": "\\wasm_importtype_new\u0028\u0029",
            "name": "wasm_importtype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_new"
        },                {
            "fqsen": "\\wasm_importtype_delete\u0028\u0029",
            "name": "wasm_importtype_delete",
            "summary": "Delete\u0020a\u0020importtype.",
            "url": "namespaces/default.html#function_wasm_importtype_delete"
        },                {
            "fqsen": "\\wasm_importtype_module\u0028\u0029",
            "name": "wasm_importtype_module",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_module"
        },                {
            "fqsen": "\\wasm_importtype_name\u0028\u0029",
            "name": "wasm_importtype_name",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_name"
        },                {
            "fqsen": "\\wasm_importtype_type\u0028\u0029",
            "name": "wasm_importtype_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_type"
        },                {
            "fqsen": "\\wasm_importtype_copy\u0028\u0029",
            "name": "wasm_importtype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_importtype_copy"
        },                {
            "fqsen": "\\wasm_exporttype_new\u0028\u0029",
            "name": "wasm_exporttype_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_exporttype_new"
        },                {
            "fqsen": "\\wasm_exporttype_delete\u0028\u0029",
            "name": "wasm_exporttype_delete",
            "summary": "Delete\u0020a\u0020exporttype.",
            "url": "namespaces/default.html#function_wasm_exporttype_delete"
        },                {
            "fqsen": "\\wasm_exporttype_name\u0028\u0029",
            "name": "wasm_exporttype_name",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_exporttype_name"
        },                {
            "fqsen": "\\wasm_exporttype_type\u0028\u0029",
            "name": "wasm_exporttype_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_exporttype_type"
        },                {
            "fqsen": "\\wasm_exporttype_copy\u0028\u0029",
            "name": "wasm_exporttype_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_exporttype_copy"
        },                {
            "fqsen": "\\wasm_val_delete\u0028\u0029",
            "name": "wasm_val_delete",
            "summary": "Delete\u0020a\u0020val.",
            "url": "namespaces/default.html#function_wasm_val_delete"
        },                {
            "fqsen": "\\wasm_val_value\u0028\u0029",
            "name": "wasm_val_value",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_value"
        },                {
            "fqsen": "\\wasm_val_kind\u0028\u0029",
            "name": "wasm_val_kind",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_kind"
        },                {
            "fqsen": "\\wasm_val_copy\u0028\u0029",
            "name": "wasm_val_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_copy"
        },                {
            "fqsen": "\\wasm_val_i32\u0028\u0029",
            "name": "wasm_val_i32",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_i32"
        },                {
            "fqsen": "\\wasm_val_i64\u0028\u0029",
            "name": "wasm_val_i64",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_i64"
        },                {
            "fqsen": "\\wasm_val_f32\u0028\u0029",
            "name": "wasm_val_f32",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_f32"
        },                {
            "fqsen": "\\wasm_val_f64\u0028\u0029",
            "name": "wasm_val_f64",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_val_f64"
        },                {
            "fqsen": "\\wasm_frame_copy\u0028\u0029",
            "name": "wasm_frame_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_copy"
        },                {
            "fqsen": "\\wasm_frame_instance\u0028\u0029",
            "name": "wasm_frame_instance",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_instance"
        },                {
            "fqsen": "\\wasm_frame_func_index\u0028\u0029",
            "name": "wasm_frame_func_index",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_func_index"
        },                {
            "fqsen": "\\wasm_frame_func_offset\u0028\u0029",
            "name": "wasm_frame_func_offset",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_func_offset"
        },                {
            "fqsen": "\\wasm_frame_module_offset\u0028\u0029",
            "name": "wasm_frame_module_offset",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_frame_module_offset"
        },                {
            "fqsen": "\\wasm_trap_new\u0028\u0029",
            "name": "wasm_trap_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_new"
        },                {
            "fqsen": "\\wasm_trap_copy\u0028\u0029",
            "name": "wasm_trap_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_copy"
        },                {
            "fqsen": "\\wasm_trap_message\u0028\u0029",
            "name": "wasm_trap_message",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_message"
        },                {
            "fqsen": "\\wasm_trap_origin\u0028\u0029",
            "name": "wasm_trap_origin",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_origin"
        },                {
            "fqsen": "\\wasm_trap_trace\u0028\u0029",
            "name": "wasm_trap_trace",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_trap_trace"
        },                {
            "fqsen": "\\wasm_module_new\u0028\u0029",
            "name": "wasm_module_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_new"
        },                {
            "fqsen": "\\wasm_module_delete\u0028\u0029",
            "name": "wasm_module_delete",
            "summary": "Delete\u0020a\u0020module.",
            "url": "namespaces/default.html#function_wasm_module_delete"
        },                {
            "fqsen": "\\wasm_module_validate\u0028\u0029",
            "name": "wasm_module_validate",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_validate"
        },                {
            "fqsen": "\\wasm_module_imports\u0028\u0029",
            "name": "wasm_module_imports",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_imports"
        },                {
            "fqsen": "\\wasm_module_exports\u0028\u0029",
            "name": "wasm_module_exports",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_exports"
        },                {
            "fqsen": "\\wasm_module_serialize\u0028\u0029",
            "name": "wasm_module_serialize",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_serialize"
        },                {
            "fqsen": "\\wasm_module_deserialize\u0028\u0029",
            "name": "wasm_module_deserialize",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_deserialize"
        },                {
            "fqsen": "\\wasm_module_name\u0028\u0029",
            "name": "wasm_module_name",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_name"
        },                {
            "fqsen": "\\wasm_module_set_name\u0028\u0029",
            "name": "wasm_module_set_name",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_set_name"
        },                {
            "fqsen": "\\wasm_module_copy\u0028\u0029",
            "name": "wasm_module_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_module_copy"
        },                {
            "fqsen": "\\wasm_func_new\u0028\u0029",
            "name": "wasm_func_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_new"
        },                {
            "fqsen": "\\wasm_func_delete\u0028\u0029",
            "name": "wasm_func_delete",
            "summary": "Delete\u0020a\u0020func.",
            "url": "namespaces/default.html#function_wasm_func_delete"
        },                {
            "fqsen": "\\wasm_func_type\u0028\u0029",
            "name": "wasm_func_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_type"
        },                {
            "fqsen": "\\wasm_func_call\u0028\u0029",
            "name": "wasm_func_call",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_call"
        },                {
            "fqsen": "\\wasm_func_as_extern\u0028\u0029",
            "name": "wasm_func_as_extern",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_func_as_extern"
        },                {
            "fqsen": "\\wasm_global_new\u0028\u0029",
            "name": "wasm_global_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_new"
        },                {
            "fqsen": "\\wasm_global_delete\u0028\u0029",
            "name": "wasm_global_delete",
            "summary": "Delete\u0020a\u0020global.",
            "url": "namespaces/default.html#function_wasm_global_delete"
        },                {
            "fqsen": "\\wasm_global_type\u0028\u0029",
            "name": "wasm_global_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_type"
        },                {
            "fqsen": "\\wasm_global_get\u0028\u0029",
            "name": "wasm_global_get",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_get"
        },                {
            "fqsen": "\\wasm_global_set\u0028\u0029",
            "name": "wasm_global_set",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_set"
        },                {
            "fqsen": "\\wasm_global_copy\u0028\u0029",
            "name": "wasm_global_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_copy"
        },                {
            "fqsen": "\\wasm_global_same\u0028\u0029",
            "name": "wasm_global_same",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_same"
        },                {
            "fqsen": "\\wasm_global_as_extern\u0028\u0029",
            "name": "wasm_global_as_extern",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_global_as_extern"
        },                {
            "fqsen": "\\wasm_extern_delete\u0028\u0029",
            "name": "wasm_extern_delete",
            "summary": "Delete\u0020an\u0020extern.",
            "url": "namespaces/default.html#function_wasm_extern_delete"
        },                {
            "fqsen": "\\wasm_extern_kind\u0028\u0029",
            "name": "wasm_extern_kind",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_kind"
        },                {
            "fqsen": "\\wasm_extern_type\u0028\u0029",
            "name": "wasm_extern_type",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_type"
        },                {
            "fqsen": "\\wasm_extern_as_func\u0028\u0029",
            "name": "wasm_extern_as_func",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_as_func"
        },                {
            "fqsen": "\\wasm_extern_as_global\u0028\u0029",
            "name": "wasm_extern_as_global",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_as_global"
        },                {
            "fqsen": "\\wasm_extern_as_table\u0028\u0029",
            "name": "wasm_extern_as_table",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_as_table"
        },                {
            "fqsen": "\\wasm_extern_as_memory\u0028\u0029",
            "name": "wasm_extern_as_memory",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_extern_as_memory"
        },                {
            "fqsen": "\\wasm_instance_new\u0028\u0029",
            "name": "wasm_instance_new",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_instance_new"
        },                {
            "fqsen": "\\wasm_instance_delete\u0028\u0029",
            "name": "wasm_instance_delete",
            "summary": "Delete\u0020an\u0020instance.",
            "url": "namespaces/default.html#function_wasm_instance_delete"
        },                {
            "fqsen": "\\wasm_instance_exports\u0028\u0029",
            "name": "wasm_instance_exports",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_instance_exports"
        },                {
            "fqsen": "\\wasm_instance_copy\u0028\u0029",
            "name": "wasm_instance_copy",
            "summary": "",
            "url": "namespaces/default.html#function_wasm_instance_copy"
        },                {
            "fqsen": "\\wasmer_version\u0028\u0029",
            "name": "wasmer_version",
            "summary": "Return\u0020the\u0020version\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version"
        },                {
            "fqsen": "\\wasmer_version_major\u0028\u0029",
            "name": "wasmer_version_major",
            "summary": "Return\u0020the\u0020major\u0020version\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version_major"
        },                {
            "fqsen": "\\wasmer_version_minor\u0028\u0029",
            "name": "wasmer_version_minor",
            "summary": "Return\u0020the\u0020minor\u0020version\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version_minor"
        },                {
            "fqsen": "\\wasmer_version_patch\u0028\u0029",
            "name": "wasmer_version_patch",
            "summary": "Return\u0020the\u0020patch\u0020version\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version_patch"
        },                {
            "fqsen": "\\wasmer_version_pre\u0028\u0029",
            "name": "wasmer_version_pre",
            "summary": "Return\u0020the\u0020pre\u002Drelease\u0020label\u0020of\u0020the\u0020Wasmer\u0020C\u0020API.",
            "url": "namespaces/default.html#function_wasmer_version_pre"
        },                {
            "fqsen": "\\wat2wasm\u0028\u0029",
            "name": "wat2wasm",
            "summary": "",
            "url": "namespaces/default.html#function_wat2wasm"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType",
            "name": "ExportType",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExportType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-ExportType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType",
            "name": "ExternType",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ExternType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-ExternType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType",
            "name": "FuncType",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\FuncType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-FuncType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType",
            "name": "GlobalType",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\GlobalType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-GlobalType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType",
            "name": "ImportType",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ImportType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-ImportType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType",
            "name": "MemoryType",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\MemoryType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-MemoryType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType",
            "name": "TableType",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\TableType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-TableType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType",
            "name": "ValType",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\ValType\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-ValType.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern",
            "name": "Extern",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Extern\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-Extern.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame",
            "name": "Frame",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Frame\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-Frame.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val",
            "name": "Val",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method___construct"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_count"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_offsetExists"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_offsetGet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_offsetSet"
        },                {
            "fqsen": "\\Wasm\\Vec\\Val\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wasm-Vec-Val.html#method_offsetUnset"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Wasm\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/wasm-exception.html"
        },                {
            "fqsen": "\\Wasm",
            "name": "Wasm",
            "summary": "",
            "url": "namespaces/wasm.html"
        },                {
            "fqsen": "\\Wasm\\Vec",
            "name": "Vec",
            "summary": "",
            "url": "namespaces/wasm-vec.html"
        }            ]
);
