<?php

declare(strict_types = 1);

namespace WASM;

const SIGNATURE_TYPE_I32 = WASM_SIGNATURE_TYPE_I32;
const SIGNATURE_TYPE_I64 = WASM_SIGNATURE_TYPE_I64;
const SIGNATURE_TYPE_F32 = WASM_SIGNATURE_TYPE_F32;
const SIGNATURE_TYPE_F64 = WASM_SIGNATURE_TYPE_F64;
const SIGNATURE_TYPE_VOID = WASM_SIGNATURE_TYPE_VOID;
